In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [55]:
# Importing base_111 file
base = pd.read_csv("base_111.csv", encoding="latin-1")
base2 = pd.read_csv("base_222.csv", encoding="latin-1")
base265 = pd.read_csv("base_265.csv", encoding="latin-1")

c:\users\hideki\appdata\local\programs\python\python36\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (15,17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [52]:
base.head(2)

Cod   Ano  Dia Juliano  Hora - minuto  \
0  111  1997          1.0             10   
1  111  1997          1.0             20   

   Veloc. Instantânea do Vento a 5 metros (m/s)  \
0                                       1618.00   
1                                          0.99   

   Veloc. Instantânea do Vento a 2 metros (m/s)  \
0                                      1115.000   
1                                         0.763   

   Direção do Vento no instante da aquisição (°)  \
0                                           8.32   
1                                          20.59   

   Radiação Incidente total de 10 leituras (KW/m2)  \
0                                              0.0   
1                                              0.0   

   Radiação Refletida Total de 10 leituras (KW/m2)  \
0                                              0.0   
1                                              0.0   

   Fluxo Positivo de calor no solo total de 10 leituras (W/m2)  \
0                                                0.0             
1                                                0.0             

   Fluxo negativo de calor no solo . total de 10 leituras (W/m2)  \
0                                             -443.0               
1                                             -443.0               

   Umidade relativa Média (%)  Temperatura do Ar Média (°C)  \
0                        92.3                         19.84   
1                        93.1                         19.63   

   Temperatura do solo  1 Média (°C) à 3cm no solo  \
0                                            21.04   
1                                            20.97   

   Temperatura do solo 2Média (°C) à 6cm no solo   \
0                                           22.68   
1                                           22.65   

  Temperatura do solo 3Média (°C) Colocado sensor de UV em 31/07/09  \
0                                              24.59                  
1                                              24.52                  

   Pressão (hPa) Chuva total do período (mm)  
0          943.0                           0  
1          943.0                           0

In [56]:
base2.head(2)

Cod   Ano  Dia Juliano  Hora - minuto  \
0  222  1997            1           2400   
1  222  1997            2           2400   

   Veloc. máxima do Vento a 5 metros (m/s)  \
0                                   6031.0   
1                                   4756.0   

   Veloc. máxima do Vento a 2 metros (m/s)  \
0                                   2677.0   
1                                   1758.0   

   Direção do Vento no instante da veloc. Máx.(°)  \
0                                            99.6   
1                                           119.5   

   Horário de ocorrência vr máx. veloc. do vento  \
0                                           1923   
1                                             45   

   Radiação Incidente Total do dia (KW/m2)  \
0                                    270.8   
1                                    165.3   

   Radiação Refletida Total do dia (KW/m2)           ...             \
0                                    53.81           ...              
1                                    27.46           ...              

   Fluxo Negativo de calor no solo. Total do dia (KW/m2)  \
0                                             -34.76       
1                                             -26.86       

  Temperatura do Ar  Máxima do dia (°C)  \
0                                 30.16   
1                                 26.15   

  Horário de ocorrência da Temp. Ar Máxima(°C)  \
0                                         1255   
1                                         1417   

  Temperatura do Ar Mínima do dia (°C)  \
0                                18.50   
1                                19.15   

   Horário de ocorrência da Temp. Ar Minima  \
0                                     551.0   
1                                    2355.0   

   Temperatura do Solo 1 Máxima do dia (°C)  \
0                                     34.53   
1                                     27.66   

  Horário de ocorrência da Temp. Solo 1 Máxima.  \
0                                          1258   
1                                          1425   

  Temperatura do Solo 1 Mínima do dia (°C)  \
0                                    19.15   
1                                    19.65   

   Horário de ocorrência da Temp. Solo 1 minima  Chuva total do dia (mm)  
0                                         606.0                      0.0  
1                                        2352.0                      0.0  

[2 rows x 21 columns]

In [57]:
base265.head(2)

Cod   Ano  Dia Juliano  Hora - minuto  Chuva das 7 h as 7 h  \
0  265  1997          1.0            700                   0.0   
1  265  1997          2.0            700                   0.0   

   Temperatura do Ar máxima do dia °C  \
0                               31.11   
1                               30.16   

   Horário de ocorrência da Temp. Ar máxima  \
0                                      1356   
1                                      1255   

   Temperatura do Ar Minima do dia (°C)  \
0                                 18.50   
1                                 19.21   

   Horário de ocorrência da Temp. Ar minima  Umidade máxima  Hora  \
0                                     551.0             NaN   NaN   
1                                     510.0             NaN   NaN   

   Umidade mínima  Hora.1  
0             NaN     NaN  
1             NaN     NaN

# Describe data

In [4]:
base.describe()

Cod           Ano   Dia Juliano  Hora - minuto  \
count  1.050445e+06  1.050445e+06  1.050445e+06   1.050445e+06   
mean   1.114778e+02  2.006549e+03  1.835618e+02   1.192104e+03   
std    9.895335e+00  5.762457e+00  1.053855e+02   6.927634e+02   
min    1.110000e+02  1.997000e+03 -5.336000e+01   1.000000e+01   
25%    1.110000e+02  2.002000e+03  9.300000e+01   6.100000e+02   
50%    1.110000e+02  2.007000e+03  1.840000e+02   1.210000e+03   
75%    1.110000e+02  2.012000e+03  2.750000e+02   1.810000e+03   
max    3.330000e+02  2.139000e+03  6.540000e+02   6.640000e+03   

       Veloc. Instantânea do Vento a 5 metros (m/s)  \
count                                  1.050445e+06   
mean                                   1.472154e+03   
std                                    1.353874e+03   
min                                   -6.999000e+03   
25%                                    1.010000e+00   
50%                                    1.481000e+03   
75%                                    2.265000e+03   
max                                    6.996000e+03   

       Veloc. Instantânea do Vento a 2 metros (m/s)  \
count                                  1.050445e+06   
mean                                   9.129840e+02   
std                                    1.134761e+03   
min                                    0.000000e+00   
25%                                    5.390000e-01   
50%                                    1.010000e+00   
75%                                    1.716000e+03   
max                                    6.999000e+03   

       Direção do Vento no instante da aquisição (°)  \
count                                   1.050445e+06   
mean                                    2.723121e+02   
std                                     6.693158e+02   
min                                     0.000000e+00   
25%                                     9.380000e+01   
50%                                     1.555000e+02   
75%                                     2.576000e+02   
max                                     6.999000e+03   

       Radiação Incidente total de 10 leituras (KW/m2)  \
count                                     1.050445e+06   
mean                                      7.622076e+02   
std                                       1.611430e+03   
min                                      -6.999000e+03   
25%                                       0.000000e+00   
50%                                       0.000000e+00   
75%                                       4.338000e+02   
max                                       6.999000e+03   

       Radiação Refletida Total de 10 leituras (KW/m2)  \
count                                     1.050445e+06   
mean                                      2.706437e+02   
std                                       8.889303e+02   
min                                       0.000000e+00   
25%                                       0.000000e+00   
50%                                       0.000000e+00   
75%                                       9.890000e-01   
max                                       6.999000e+03   

       Fluxo Positivo de calor no solo total de 10 leituras (W/m2)  \
count                                       1.050445e+06             
mean                                        3.653693e+02             
std                                         1.147225e+03             
min                                         0.000000e+00             
25%                                         0.000000e+00             
50%                                         0.000000e+00             
75%                                         1.788000e+02             
max                                         6.999000e+03             

       Fluxo negativo de calor no solo . total de 10 leituras (W/m2)  \
count                                       1.048620e+06               
mean                                       -1.662485e+03               
std                            

Here we can see that there are a few values inconsistent, like negative value for "Day's variable"

In [5]:
#Counting 0 value for Day variable
base[base['Dia Juliano'] <1 ]['Ano'].nunique()

2

In [6]:
#Looking these values
base[base['Dia Juliano'] <1 ]['Dia Juliano'].unique()

array([-53.36,   0.  ])

In [7]:
#Looking which Years tehse inconsistent values exist
base[base['Dia Juliano'] <1 ]['Ano'].unique()

array([2019, 2000], dtype=int64)

Also there are values above 366 in Day Variable

In [9]:
#Looking
base[base['Dia Juliano'] > 366 ]['Dia Juliano'].unique()

array([ 388.,  654.])

In [10]:
#Looking years of occurence
base[base['Dia Juliano'] > 366 ]['Ano'].unique()

array([2039, 2139], dtype=int64)

Since out datasets are from 1997 to 2017 values above 2017 are also inconsistent

In [11]:
#Couting inconsistent values
base[base['Ano']> 2017]['Ano'].nunique()

4

In [12]:
#Looking these values
base[base['Ano']> 2017]['Ano'].unique()

array([2019, 2039, 2126, 2139], dtype=int64)

Other variable with directly notable inconsistent values is "Hora - Minuto" that is hour variable, it is limited from 0 to 2400

In [13]:
#counting
base[base['Hora - minuto']> 2400]['Hora - minuto'].nunique()

1

In [14]:
#looking
base[base['Hora - minuto']> 2400]['Hora - minuto'].unique()

array([6640], dtype=int64)

All these values will be tagged to future treatment

# Missing values

In [15]:
base.isnull().sum()

Cod                                                                     0
Ano                                                                     0
Dia Juliano                                                             0
Hora - minuto                                                           0
Veloc. Instantânea do Vento a 5 metros (m/s)                            0
Veloc. Instantânea do Vento a 2 metros (m/s)                            0
Direção do Vento no instante da aquisição (°)                           0
Radiação Incidente total de 10 leituras (KW/m2)                         0
Radiação Refletida Total de 10 leituras (KW/m2)                         0
Fluxo Positivo de calor no solo total de 10 leituras (W/m2)             0
Fluxo negativo de calor no solo . total de 10 leituras (W/m2)        1825
Umidade relativa Média (%)                                           1826
Temperatura do Ar Média (°C)                                         1826
Temperatura do solo  1 Média (°C) à 3c

In [18]:
#Counting all
base.isnull().sum().sum()

16432

These values will be also tagged later

# Fixing inconsistent values

In [19]:
#Function to fix year variable
def fix_year(anos):
    if(anos in [2019, 2039, 2126, 2139]):
        return -999
    else:
        return anos

In [20]:
base['Ano'] = base['Ano'].map(fix_year)

In [21]:
#Function to fix hour variable
def fix_hour(hours):
    if(hours == 6640):
        return -999
    else:
        return hours

In [22]:
base["Hora - minuto"] = base["Hora - minuto"].map(fix_hour)

In [23]:
#Function to fix day variable
def fix_day(days):
    if((days<1) | (days > 366)):
        return -999
    else:
        return days

In [24]:
base["Dia Juliano"] = base["Dia Juliano"].map(fix_day)

In [25]:
base = base.dropna();

In [26]:
base.shape

(1048254, 18)

# Checking data consistency

In [27]:
base.isnull().sum()

Cod                                                                  0
Ano                                                                  0
Dia Juliano                                                          0
Hora - minuto                                                        0
Veloc. Instantânea do Vento a 5 metros (m/s)                         0
Veloc. Instantânea do Vento a 2 metros (m/s)                         0
Direção do Vento no instante da aquisição (°)                        0
Radiação Incidente total de 10 leituras (KW/m2)                      0
Radiação Refletida Total de 10 leituras (KW/m2)                      0
Fluxo Positivo de calor no solo total de 10 leituras (W/m2)          0
Fluxo negativo de calor no solo . total de 10 leituras (W/m2)        0
Umidade relativa Média (%)                                           0
Temperatura do Ar Média (°C)                                         0
Temperatura do solo  1 Média (°C) à 3cm no solo                      0
Temper

In [28]:
base[(base['Dia Juliano'] <1 ) & (base['Dia Juliano']!=-999)]['Ano'].nunique()

0

In [29]:
base[base['Ano']> 2017]['Ano'].nunique()

0

In [30]:
base[base['Hora - minuto']> 2400]['Hora - minuto'].nunique()

0

# Treatment of variables with non numerical data, where it should be

In [31]:
vars_ = base.columns

In [32]:
for v in vars_: 
    try:
        base[v] = base[v].astype(float)
    except ValueError:
    #Handle the exception
        print("Theres is non numerical data in variable : ", v)

Theres is non numerical data in variable :  Temperatura do solo 3Média (°C) Colocado sensor de UV em 31/07/09
Theres is non numerical data in variable :  Chuva total do período (mm)


In [33]:
#Fixing these values

base['Temperatura do solo 3Média (°C) Colocado sensor de UV em 31/07/09'] = pd.to_numeric(base['Temperatura do solo 3Média (°C) Colocado sensor de UV em 31/07/09'], errors='coerce')
base['Chuva total do período (mm)']= pd.to_numeric(base['Chuva total do período (mm)'], errors = 'coerce')

In [34]:
base = base.dropna();

In [37]:
base.isnull().sum()

Cod                                                                  0
Ano                                                                  0
Dia Juliano                                                          0
Hora - minuto                                                        0
Veloc. Instantânea do Vento a 5 metros (m/s)                         0
Veloc. Instantânea do Vento a 2 metros (m/s)                         0
Direção do Vento no instante da aquisição (°)                        0
Radiação Incidente total de 10 leituras (KW/m2)                      0
Radiação Refletida Total de 10 leituras (KW/m2)                      0
Fluxo Positivo de calor no solo total de 10 leituras (W/m2)          0
Fluxo negativo de calor no solo . total de 10 leituras (W/m2)        0
Umidade relativa Média (%)                                           0
Temperatura do Ar Média (°C)                                         0
Temperatura do solo  1 Média (°C) à 3cm no solo                      0
Temper

In [45]:
((base == -1000) | (base == -999)).sum()

Cod                                                                    0
Ano                                                                  128
Dia Juliano                                                          131
Hora - minuto                                                          1
Veloc. Instantânea do Vento a 5 metros (m/s)                           0
Veloc. Instantânea do Vento a 2 metros (m/s)                           0
Direção do Vento no instante da aquisição (°)                          0
Radiação Incidente total de 10 leituras (KW/m2)                        0
Radiação Refletida Total de 10 leituras (KW/m2)                        0
Fluxo Positivo de calor no solo total de 10 leituras (W/m2)            0
Fluxo negativo de calor no solo . total de 10 leituras (W/m2)         20
Umidade relativa Média (%)                                             0
Temperatura do Ar Média (°C)                                           0
Temperatura do solo  1 Média (°C) à 3cm no solo    

In [49]:
clean_base = base[((base != -1000) & (base != -999))]
clean_base = clean_base.dropna();

In [50]:
# Here we export our main resulted dataset of this code
clean_base.to_csv("clean_base111.csv", index = False)